language: rust
rust:
  - stable
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
    - os: windows
    - os: mac
  fast_finish: true
script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all
os:
  - linux
  - windows
  - mac