language: rust
rust:
  - stable
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
    - os: windows
    - os: mac
  fast_finish: true
script:
  - cargo build --verbose --workspace
  - git clone https://github.com/firehol/blocklist-ipsets.git blocklist-ipsets
  - cargo test --verbose --workspace
os:
  - linux
  - windows
  - mac