language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all
os:
  - linux
  - windows