[package]
name = "ipset-lookup"
version = "0.1.1"
authors = ["Taneli Kaivola <tanelikaivola@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
ipnetwork = "0.16.0"
rayon = "1.3.0"
clap = "2.0.0"
